name: Sync Data
on:
  push:
    paths:
      - 'data.json'
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync data
        run: |
          echo "Data synced at $(date)" >> sync.log
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Sync data" || exit 0
          git push
