#!/usr/bin/env python3
"""
Script to help fix Render deployment settings
"""

def print_render_instructions():
    """Print detailed instructions for fixing Render settings"""
    
    print("🚀============================================================")
    print("🚀  CASHPOT V5 - RENDER SETTINGS FIX")
    print("============================================================\n")
    
    print("❌ PROBLEMA: Render încă folosește comanda veche!")
    print("   Comanda actuală: pip install -r requirements.txt")
    print("   Comanda corectă: pip install -r \"Downloads/cash-pot v5 copy/requirements.txt\"")
    print()
    
    print("🔧 SOLUȚIA - Urmărește acești pași EXACT:")
    print()
    print("1️⃣  Deschide Render Dashboard:")
    print("   https://dashboard.render.com")
    print()
    print("2️⃣  Găsește serviciul tău:")
    print("   - Click pe serviciul 'cashpot-backend'")
    print("   - Sau orice nume ai dat serviciului")
    print()
    print("3️⃣  Click pe 'Settings' din sidebar stânga")
    print()
    print("4️⃣  În secțiunea 'Build & Deploy':")
    print("   - Build Command: pip install -r \"Downloads/cash-pot v5 copy/requirements.txt\"")
    print("   - Start Command: python \"Downloads/cash-pot v5 copy/server.py\"")
    print("   - Root Directory: (șterge tot ce e acolo, lasă gol)")
    print()
    print("5️⃣  În secțiunea 'Environment Variables':")
    print("   - MONGO_URL: mongodb://localhost:27017")
    print("   - JWT_SECRET_KEY: (click Generate)")
    print("   - JWT_ALGORITHM: HS256")
    print("   - JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30")
    print("   - CORS_ORIGINS: [\"https://jeka7ro.github.io\", \"https://jeka7ro.github.io/cashpot-v5\"]")
    print("   - SECRET_KEY: (click Generate)")
    print("   - ENVIRONMENT: production")
    print("   - DEBUG: False")
    print()
    print("6️⃣  Click 'Save Changes'")
    print()
    print("7️⃣  Click 'Manual Deploy'")
    print()
    print("✅ REZULTATUL AȘTEPTAT:")
    print("   ==> Running build command 'pip install -r \"Downloads/cash-pot v5 copy/requirements.txt\"'...")
    print("   ==> Installing fastapi==0.100.0")
    print("   ==> Installing uvicorn==0.23.0")
    print("   ==> Installing pymongo==4.5.0")
    print("   ==> Installing bcrypt==4.0.1")
    print("   ==> Installing python-jose==3.3.0")
    print("   ==> Installing python-multipart==0.0.6")
    print("   ==> Installing python-dotenv==1.0.0")
    print("   ==> Installing pydantic==1.10.12")
    print("   ==> Build successful! ✅")
    print("   ==> Starting server...")
    print("   ==> Server running on port 10000")
    print()
    print("🚨 IMPORTANT: Dacă nu vezi aceste comenzi, înseamnă că")
    print("   setările nu s-au salvat corect. Încearcă din nou!")
    print()
    print("📞 Dacă tot nu merge, trimite-mi screenshot cu setările")
    print("   din Render dashboard să văd ce se întâmplă.")

if __name__ == "__main__":
    print_render_instructions()
